name: code-quality
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  linting:
    name: linting
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Static check
        uses: reviewdog/action-staticcheck@v1
        with:
          # Change reviewdog reporter if you need [github-pr-check,github-check,github-pr-review].
          reporter: github-pr-review
          # Report all results.
          filter_mode: nofilter

      - name: Run linting check
        uses: reviewdog/action-golangci-lint@v2
        with:
          # optionally use a specific version of Go rather than the latest one
          reporter: github-pr-review
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Setup Golang with cache
        uses: magnetikonline/action-golang-cache@v3
        with:
          go-version-file: go.mod
      - name: Build
        run: make build
      - name: Run test coverage
        run: go test ./... -race -coverprofile=coverage.out -covermode=atomic
